inkua/information-technology-it-workspace

- Habits.md
Posible estructura a tomar en cuenta para el día a día
> Nuevo archivo habits.md

- projects/tp1/Vladimir-Maidana-Acarapi/index.html
- projects/tp1/Vladimir-Maidana-Acarapi/readme.md
> Work Completed - Vladimir Maidana

- projects/tp1/Ricardo-Yepez/index.html
- projects/tp1/Ricardo-Yepez/readme.md
Añado mis archivos para cumplir con el Trabajo Práctico 1.
> Cv Ricardo Yepez

- projects/tp1/manuel-esteban-florez-lopez/index.html
- projects/tp1/manuel-esteban-florez-lopez/readme.md
Entrego la practica de InkuA pt1, algun a progunta me pueden enviar un mail a manuel14mds@gmail.com
> project finished

- projects/landing/index.html
- projects/landing/styles.css
This request just contains the structure on what the team will work on this week: 
- Mario Chavez: SECTION 2 & 3
- Andrés Campos: SECTION 4
- Erick Arias: SECTION 5 & 6
- Debora Cuestas: SECTION 7
- Pedro Gascon: SECTION 8 (FOOTER)
*Thanks*
> Team structure sections

- projects/landing/css/sobre-nosotros.css
- projects/landing/pages/sobre-nosotros.html
> Team Structure Sobre Nosotros Page

- projects/landing/css/index.css
- projects/landing/index.html
> refa-section-4

- projects/landing/css/sobre-nosotros.css
- projects/landing/pages/sobre-nosotros.html
Seccioón 3 de Pagina Sobre nosostros agregada
> Agregada Sección 3 de pagina sobre nosotros

- projects/landing/css/sobre-nosotros.css
- projects/landing/pages/sobre-nosotros.html
Correcciones agregadas a CSS y HTML
> Correcciones agregadas

- projects/landing/css/index.css
> Refaction of section7

- projects/caballos-en-libertad/assets/css/index.css
- projects/caballos-en-libertad/scaffolding.html
Documentos añadidos
projects/caballos-en-libertad/assets/css/index.css
projects/caballos-en-libertad/scaffolding.html
> vars CSS and scaffolding added

- projects/landing/css/forma-parte.css
- projects/landing/pages/forma-parte.html
> Sección 5 finalizada

- projects/landing/css/donar.css
- projects/landing/css/ingresar.css
- projects/landing/pages/donar.html
- projects/landing/pages/ingresar.html
> add page get into

- projects/landing/css/forma-parte.css
- projects/landing/pages/forma-parte.html
Section number 1 of FP was added
> Section number 1 of FP was added

- projects/caballos-en-libertad/adoptar.html
- projects/caballos-en-libertad/assets/css/adoptar_style.css
Modifique el import y agregue el color four
> modificando imports y color

- projects/landing/hide.js
- projects/landing/pages/ingresar.html
Hello Erick.
Send add-hide-eye
> add-hide-eye

- projects/landing/css/forma-parte.css
- projects/landing/pages/forma-parte.html
Se agregan cambios en la seccion 3 de la pagina "formar parte"
> agregando cambios css y html

- projects/landing/css/donar.css
- projects/landing/pages/donar.html
> add donar-section-one

- projects/caballos-en-libertad/assets/css/eventos.css
- projects/caballos-en-libertad/eventos.html
-Se modificó de boostrap 4 a 5.
-Se agregó el footer.
-Se agregó responsiveness.
> nuevos cambios

- projects/landing/css/donar.css
- projects/landing/pages/donar.html
Ajuste pendiente: La imágen no queda centrada en todos los tamaños de pantalla
> Section4 donar

- projects/caballos-en-libertad/assets/css/denuncias.css
- projects/caballos-en-libertad/assets/css/main_style.css
- projects/caballos-en-libertad/denuncias.html
**Sección Denuncias**:
- Agregado imagen, iconos, título y descripción principal (version desktop)
- Agregado difuminado/filtro gris horizontal al background imagen del título.
- Incorporados header y footer.
- Incorporado icono de WhattsApp.
- Arreglos menores.
**Icono de WhattsApp**:
- modificado centrado icono y texto versión desktop (index.css).
> Sección denuncias - agregado título, imagenes y más.

- projects/caballos-en-libertad/assets/css/main_style.css
- projects/caballos-en-libertad/index.html
Hago entrega de la seccion de caballos rescatados terminada
- He añadido el mensaje que aparece debajo del container de imagenes de caballos
> Caballos en libertad - adding recatados seccion message

- projects/caballos-en-libertad/assets/css/main_style.css
- projects/caballos-en-libertad/index.html
- Quitando el scroll en la parte del contenedor de imagenes de caballos.
- Arreglando el los estilos de los modal.
- Añadiendo el link en mas Info a caballos que le funciona el link.
> Caballos en Libertad - taking scroll rescatados off

- projects/caballos-en-libertad/assets/css/voluntariado_style.css
- projects/caballos-en-libertad/index.html
Realicé la mejora detallada en trello y además hice algunas otras correcciones
> Voluntariado

- projects/caballos-en-libertad/assets/css/denuncias.css
- projects/caballos-en-libertad/pages/denuncias.html
- Arreglos visuales en la vista de móvil en la sección de denuncias.
- Arreglos visuales en la vista de escritorio en la sección de denuncias.
- Arreglos visuales finalizados.
> Caballos en Libertad - Arreglos sección denuncias

- projects/caballos-en-libertad/assets/css/main_style.css
- projects/caballos-en-libertad/index.html
> Caballos En Libertad - fix sobreNosotros

- projects/caballos-en-libertad/assets/css/index.css
- projects/caballos-en-libertad/assets/css/main_style.css
- projects/caballos-en-libertad/index.html
- projects/caballos-en-libertad/pages/adoptar.html
- projects/caballos-en-libertad/pages/denuncias.html
- projects/caballos-en-libertad/pages/eventos.html
Entrego el diseño del footer ya full responsive
> Cabballos en libertad footer

- projects/caballos-en-libertad/assets/css/main_style.css
- projects/caballos-en-libertad/index.html
Tarea realizada.
-Añadido *max-widht* a la etiqueta main.
Detalles visuales extra ( solo en pantallas extra-anchas )
-Agregado *--color-four* a los laterales extremos.
-Agregada *sombras laterales* después del ancho máximo del main.
> Main, tamaño máximo añadido

- projects/caballos-en-libertad/assets/css/voluntariado_style.css
- projects/caballos-en-libertad/index.html
**Sección Voluntariado - Trabajado en detalles visuales que faltaron siguiendo diseño en figma:**
-Agregado borde curvo en los extremos inferior y superior (vista movile).
-Agregado recuadro en background-color: var(--color-three) para el contenido general y fondo blanco para el título (Vistas tablet y desktop).
-Agregado padding y margin respetando el diseño.
-Modificado minimamente tamaño del título (vista movile).
> Cab. en Libertad - Seccion voluntariado (Mejoras)

- projects/caballos-en-libertad/index.html
- projects/caballos-en-libertad/pages/adoptar.html
- projects/caballos-en-libertad/pages/denuncias.html
- projects/caballos-en-libertad/pages/eventos.html
- Actualizados todos los links de WhattsApp en todas las páginas.
- Ligero cambio en el HTML del icono de WhattsApp para que todo contorno del botón sea clickeable (en todas las páginas)
> Cab. en Libertad - Actualización href WhattsApp

- projects/caballos-en-libertad/index.html
- projects/caballos-en-libertad/pages/adoptar.html
- projects/caballos-en-libertad/pages/denuncias.html
- projects/caballos-en-libertad/pages/eventos.html
- Creado link hacia MercadoPago en la imagen de MercadoPago del modal.
> Cab. en Libertad - Sección Donar

- projects/caballos-en-libertad/assets/css/denuncias.css
- projects/caballos-en-libertad/index.html
- projects/caballos-en-libertad/pages/adoptar.html
- projects/caballos-en-libertad/pages/denuncias.html
- projects/caballos-en-libertad/pages/eventos.html
- Arreglado sombra inferior (Vista desktop máxima).
- Arreglado tamaño muy alto de imagen principal (Vista desktop máxima).
> Cab. en Libertad - Seccion Denuncias

- projects/caballos-en-libertad/assets/css/adoptar_style.css
- projects/caballos-en-libertad/index.html
- projects/caballos-en-libertad/pages/adoptar.html
Actividades de Trello: 
-Botón 'Comunicarme'
-Agregar teléfono sección 'Contacto'
> Mejora sección Adoptar

- projects/uao-ukraine-assistance-organization/index.html
Done the main title from my section
> Adding the main title from gabriel's section

- projects/uao-ukraine-assistance-organization/index.html
Buenas tardes, agregue mi nombre como practica para los comandos de github
> Agregue mi nombre

- .vscode/settings.json
- projects/uao-ukraine-assistance-organization/index.html
En la sección GET INVOLVED se añadió estructura HTML sin modificar el index.css
> Se modificó solamente la estructura HTML para la sección de GET INVOLVED

- projects/uao-ukraine-assistance-organization/css/index.css
Se realizaron últimos cambios con respecto a la sección Get Involved.
> Se hicieron cambios minimos en el css con respecto a la seccion Get Involved

- projects/uao-ukraine-assistance-organization/css/index.css
- projects/uao-ukraine-assistance-organization/index.html
- projects/uao-ukraine-assistance-organization/scripts.js
In this PR we made the header for our section, the description and the carousel.
Left items: 
- Description in each photo of the carousel
- Initial slide
> Make stories, add header, description and carousel

- projects/caballos-en-libertad/assets/css/index.css
- projects/caballos-en-libertad/index.html
- projects/caballos-en-libertad/pages/adoptar.html
- projects/caballos-en-libertad/pages/denuncias.html
- projects/caballos-en-libertad/pages/eventos.html
> easter egg footer collaborators

- projects/uao-ukraine-assistance-organization/css/index.css
- projects/uao-ukraine-assistance-organization/index.html
- projects/uao-ukraine-assistance-organization/scripts.js
Cambio de fuente de h1 y animacion
> Cambio de fuente del h1 y agregado de animacion

- projects/uao-ukraine-assistance-organization/css/index.css
Add media queries Section Contact Us to improve Responsive
> Add Media Querys Contact Us

- projects/human-front-aid/index.html
Agregada carpetas del proyecto.
Agregado archivo index.html con un header básico. 
Agregado un archivo index.css.
> Human Front Aid - Primer Commit

- projects/human-front-aid/css/general-styles.css
- projects/human-front-aid/css/index.css
- projects/human-front-aid/index.html
-Realizado el navbar con todos sus botones.
-Agregado en header link a Google Fonts.
-Agregado archivo general-styles.css con colores básicos y fuentes de texto.
-Falta enlazar los links a las diferentes páginas.
-Falta agregar imagen de fondo.
> Human Front Aid - Sección Navbar

- projects/human-front-aid/about-us.html
- projects/human-front-aid/index.html
Aplicados los cambios realizados en header de index.html realizados por un compañero.
Agregado textos como en el diseño.
> Human Front Aid - Aplicando cambios al header en index.html

- projects/human-front-aid/about-us.html
- projects/human-front-aid/css/about-us.css
- projects/human-front-aid/index.html
- Agregados breakpoints de 767px y 768px para las resoluciones de movile y desktop.
- Creado un archivo about-us.css para separar contenidos.
- Aplicados Header y Footer de la sección about-us a la de home.
- Falta considerar agregar más breakpoints para una mejor visualización de la página en más resoluciones.
> Human Front Aid - Arreglos generales

- projects/human-front-aid/css/help.css
- projects/human-front-aid/pages/help.html
Adelanto el desarrollo de la lista de ONGs en la pagina de la Página "Want to help?"
> first contribution Help page - HUMAN-FRONT-AID

- projects/human-front-aid/about-us.html
- projects/human-front-aid/css/index.css
- projects/human-front-aid/index.html
- projects/human-front-aid/js/chatbot.js
> Desvanecimiento Btn ChatBot

- projects/human-front-aid/about-us.html
- Arreglado errores en el header
> HFAID - Header cambios

- projects/human-front-aid/css/index.css
- projects/human-front-aid/index.html
- Elimina estilos CSS para mobile del apartado Footer en la vista Home.
- Actualiza estilos CSS del apartado Footer en la visa Home ya existente.
- Establece las rutas correctas en las etiquetas 'a' en el Hmtl en la sección Home para el footer.
> HFAID - home-footer-modificacion

- projects/human-front-aid/css/general-styles.css
- projects/human-front-aid/css/index.css
- projects/human-front-aid/index.html
- Arreglos en el código de sección Supporters.
- Agregados nuevos breakpoints.
- Agregado nuevas variables de margin.
> HFAID - Sección Home

- projects/human-front-aid/css/want-to-help.css
- projects/human-front-aid/pages/want-to-help.html
Actualizacion titulo de la pagina Want to help.
> update ONGs title

- projects/human-front-aid/css/index.css
> Agrega estilos en la sección footer, para dimension de pantalla mobile, en la pagina home.
> HFAID - Agrega estilos a la sección Footer, para dimension de pantalla mobile, en la pagina home.

- projects/human-front-aid/css/general-styles.css
- projects/human-front-aid/css/index.css
- projects/human-front-aid/index.html
- projects/human-front-aid/pages/about-us.html
> style (titles): modifying the home titles stytle

- projects/human-front-aid/css/general-styles.css
- projects/human-front-aid/css/index.css
- projects/human-front-aid/index.html
- Arreglo de espacios en los subtitulos de contenido.
- Se movió el código css en el archivo general_styles.css, se cambiaron nombres y eliminaron el código anterior.
- Utilización de nuevo formato para el código html.
- Utilización de nomenclatura rem.
> HFAID - Home - content titles and code fix

- .gitmodules
This project, lovingly crafted by @bairon-cano, @JuniorCalva40, and @CMacxC, is for the "Fundacion Benefica Internacional Vash Gorod". It serves as a template to assist new developers in creating pages for NGOs.
The project has been incorporated as a submodule, given that it maintains its own repository, which can be found here: `https://github.com/inkua/maqueta-ong`.
For further information on git modules, GitHub provides comprehensive documentation that can be accessed here: `https://github.blog/2016-02-01-working-with-submodules/`.
> `ADD` `GITMODULE` maqueta-ong

- projects/human-front-aid/css/index.css
Se arregló el bug que hacia que la ventana del chatbot aparezca abierta al cargar la página.
> HFAID - chatbot bug fixed

- projects/human-front-aid/css/general-styles.css
- projects/human-front-aid/pages/about-us.html
- projects/human-front-aid/pages/need-help.html
- projects/human-front-aid/pages/want-to-help.html
Cambios en la sección Chatbot:
- Se cambiaron las dimensiones en la versión mobile.
- Se actualizó y adaptó dicha sección en todas las páginas.
> HFAID - Chatbot - fix and applied in all pages.

- projects/human-front-aid/css/general-styles.css
- Se mejoró la sección gris de la ventana del chatbot en la vista de mobile, manteniendo sus dimensiones en los distintos tamaños de pantalla.
> HFAID - Chatbot - improved gray section.

- projects/human-front-aid/css/general-styles.css
- projects/human-front-aid/index.html
- projects/human-front-aid/pages/about-us.html
- projects/human-front-aid/pages/need-help.html
- projects/human-front-aid/pages/want-to-help.html
- Se corrigió, de forma exacta, el tamaño de la ventana del Chatbot en los diferentes tamaños de pantalla mobile.
- Se corrigió un error en el código que generaba que los iconos del chatbot se muevan hacia abajo, fuera de su cuadro, en los tamaños más pequeños de la vista mobile.
> HFAID - Chatbot - window and icons mobile fixed.

- projects/human-front-aid/css/index.css
- projects/human-front-aid/index.html
I do both task in only one PR because it is the same section
https://github.com/inkua/information-technology-it-workspace/assets/89274119/0b898253-3a2a-4ff8-965a-f2b62ba7976a
> HFAID button & image about section

- projects/human-front-aid/css/general-styles.css
- Se agregó una sección nueva de extra querys en el archivo general_styles.css para mejorar el ancho del contenido (vrs. tablet y desktop).
- Se corrigió la altura del footer y se centró el contenido.
- Se redujo el tamaño de los textos de acceso a las redes sociales.
> HFAID - Footer - fixed dimension details.

- projects/human-front-aid/css/need-help.css
- projects/human-front-aid/css/want-to-help.css
- Se corrigió el ancho de pantalla en todas las vistas de las páginas Need Help y Want to Help, que tenían un error con los tamaños más pequeños de pantalla.
> HFAID - Header - fixed widths

- projects/human-front-aid/css/general-styles.css
- projects/human-front-aid/index.html
- Se separó el código que da efectos de hover a los botones para que puedan aplicarlo desde el header y el footer.
- Se aplicaron los correspondientes efectos de hover en los botones del footer.
- Se corrigieron los tamaños de cuadros y letras que corresponde a los botones de navegación del footer en todas las vistas.
> HFAID - Footer - buttons fixed

- projects/human-front-aid/pages/about-us.html
- projects/human-front-aid/pages/need-help.html
- projects/human-front-aid/pages/want-to-help.html
- Se aplicaron los efectos de los botones en todas las páginas.
- Se modificaron las etiquetas HTML implicadas para mejorar la visibilidad e intuitividad del código.
> Navbar -  Buttons effect applied on all pages

- projects/human-front-aid/css/general-styles.css
- projects/human-front-aid/index.html
- projects/human-front-aid/pages/about-us.html
- projects/human-front-aid/pages/need-help.html
- projects/human-front-aid/pages/want-to-help.html
- Se crearon clases e identificadores nuevos que contienen sólo los estilos de subrayado.
- Se aplicaron dichas clases a las etiquetas HTML de las secciones, Header y Footer.
- Se corrigieron errores generados al aplicar los nuevos efectos.
> HFAID - General - added underline effect.

- projects/human-front-aid/css/want-to-help.css
- projects/human-front-aid/pages/want-to-help.html
Se agregó una clase para efectos de sombra a los botones y al QR activo de la sección Donate dentro del header.
> Donate - shadow effect added.

- projects/human-front-aid/css/want-to-help.css
- projects/human-front-aid/js/cambioQR.js
- Cambio de disposición de los botones y el QR más fiel al diseño en Figma.
- Se agregó un efecto de scrool al momento de clickear un botón, para una mejor visualización del cambio de QR (Tablet).
- Se movieros los demás elementos para que el QR pueda tener su propio espacio por debajo del header.
> HFAID - Donate - Tablet view improvements.

- projects/human-front-aid/css/want-to-help.css
- Se agregó una modificación al título principal, en la versión tablet para que pueda visualizarse correctamente los botones de QR y el QR en sí.
> Donate - Tittle header tablet fixed.

- projects/human-front-aid/css/want-to-help.css
- Se corrigieron los subtítulos, aumentando el tamaño de espacio y justificando el texto, sección Header.
- Se mejoró el posicionamiento de la imagen QR en la vista tablet y desktop.
- Se agregó una media query extra para desktop.
- Se agregaron algunos espaciados en el código CSS de la página Want to Help, siguiendo la metodología acordada.
> Donate - position image QR fixed.

- projects/human-front-aid/css/about-us.css
- Se redujo el grosor de todo el texto para hacerlo más parecido al diseño.
- Se corrigieron espacios en el archivo about-us.css respetando la metodología acordada.
> HFAID - About us - Text correction

- projects/human-front-aid/css/general-styles.css
- Se agregaron extraquerys para el Header en las versiones más pequeñas en tamaño de pantalla de Tablet.
- Se mejoró la disposición de los botones de navegación en la vista Tablet.
> Header - improved tablet view.

- projects/human-front-aid/css/want-to-help.css
- projects/human-front-aid/pages/want-to-help.html
- Se corrigió el tamaño de los subtítulos para que los botones de QR y la imagen QR no se muevan.
- Se corrigió el espacio en blanco que se generaba en pantallas pequeñas, en la versión Tablet.
- Se corrigió la posición vertical de la imagen QR en la vista Tablet.
> Donate - subtitles and QR fixed.

- projects/human-front-aid/css/general-styles.css
- projects/human-front-aid/css/index.css
- projects/human-front-aid/js/carouselPressAndNews.js
SECCIÓN PRESS AND NEWS - PÁGINA HOME
- Se arregló el espacio en blanco debajo del carrusel.
- Se arregló el pequeño espacio entrecortado en la parte superior del carrusel (Mobile).
- Se mejoró el efecto de sombra (Mobile).
- Se agregó efecto de autoplay (Todas las vistas) e infinite loop (Mobile).
- Se redujo el espacio superior e inferior de los subtítulos de color azul (Mobile).
> PressAndNews - carousel mobile fixed.

- projects/human-front-aid/css/index.css
- projects/human-front-aid/index.html
- projects/human-front-aid/js/carouselPressAndNews.js
SECCIÓN PRESS-AND-NEWS - PÁGINA HOME
- Se corrigió el espacio extra entre el carrusel y los indicators (versión Tablet).
- Se corrigió el corte superior en el carrusel (versión Desktop). 
- Se extendió de horizontalmente el espacio del carrusel de forma que se paresca más al diseño (Todas las versiones).
- Se agrego efecto de autoplay (Todas las versiones).
- Se agregaron sombras correspondientes a las tarjetas del carrusel (Todas las versiones).
- Se cambió los links de forma que al hacer click en cada imagen se redireccione al enlace correspondiente.
- Se cambió ligeramente el efecto de hover en las tarjetas del carrusel (Todas las versiones).
- Se eliminó código antiguo innecesario.
> PressAndNews - fixes in tablet, desktop version.

- projects/human-front-aid/css/want-to-help.css
- projects/human-front-aid/js/language/language.js
Se ajusto el CSS eliminando la versión “.icono-paypal-active:hover” del botón activo para que no cambie de color una vez seleccionado.
> Donate - Botones QR mejora (Tablet y Desktop)

- projects/human-front-aid/css/index.css
- projects/human-front-aid/index.html
- projects/human-front-aid/js/swiper-supporters.js
Mejoras realizadas:
- Se arreglo el error de los indicadores y cambios de pantalla (ahora funcionan correctamente).
- Se cambio el código de cada una de las cartas de forma que se puedan clickear más facilmente y se abran en una ventana aparte.
- Se mejoro el tamaño del carrusel y sus cartas e imagenes en todas las vistas.
- Se cambió el ancho total del carrusel.
- Se actualizaron los links que no funcionaban.
> HFAID - Supporters - improvement made.

- projects/human-front-aid/index.html
- projects/human-front-aid/js/language/language_en_data.js
- projects/human-front-aid/js/language/language_uc_data.js
- projects/human-front-aid/pages/about-us.html
- projects/human-front-aid/pages/donate.html
- projects/human-front-aid/pages/need-help.html
- Se corrigió un pequeño error que hacia que la opción donate se vea como undefined en la versión mobile.
- Se actualizó el botón amarillo de donaciones ubicado en la página home.
> HFAID - Header

- projects/tp1/santiago-larrosa-bauza/index.html
- projects/tp1/santiago-larrosa-bauza/readme.md
> Pull Request para entregar el práctico de Santiago Larrosa Bauzá

- projects/human-front-aid/pages/donate.html
- projects/resto/index.html
> resto - creacion del espacio

- projects/tp1/julian-alvarez/index.html
- projects/tp1/julian-alvarez/readme.md
-   Soy Julian Alvarez, tengo 21 años. Estudio desarrollo de software en la localidad de Cordoba, 
asi mismo continuo reforzando mis estudios de manera virtual con cursos de manera autonoma.
Estoy casado para poder mudarme a España con mi actual esposa. Soy un aficionado de la tecnologia
y la mayoria de sus ramas me llaman la atencion.
-   Debido al tiempo estimado para realizar el practico, utilice de JavaScript, para alertas y funciones
de ocultar elementos. Tambien CSS para darle estilo al maquetado y HTML para introducir informacion
en la web.
-   Me parece una idea innovadora ya que no la pude ver en otras recultaciones de trabajo. Una buena
opcion de demostrar conocimientos.
> julian-alvarez

- projects/tp1/Gonzalo-Ezequiel-Vega-Echeverria/index.html
- projects/tp1/Gonzalo-Ezequiel-Vega-Echeverria/readme.md
Trabajo InkuA Gonzalo Ezequiel Vega Echeverría.
> Trabajo InkuA Gonzalo Vega

- projects/resto/Readme.md
(add)profile linkedin melani-depetris
> (add)profile linkedin melani-depetris

- projects/resto/Readme.md
Link a Linkedin Faustino Harriague
> Link Faustino

- projects/resto/Readme.md
> firt pull and update readme.md

- projects/resto/Readme.md
- readme.md
Correción de mi nombre y linkedin ahora en el lugar correcto en Resto + tarea git flow
> F1-T3-5 feat/slarrosa Git Flow

- projects/resto/cv/melani-depetris.html
F2-T1-1-feat html semantic for cv/MDepetris
> F2-T1-1 feat/MDepetris

- projects/resto/cv/css/pricing.css
- projects/resto/cv/melani-depetris.html
F2-T2-2- feat maquetado responsive :)
> F2-T2-2- feat maquetado responsive

- projects/tp1/felipe-blanco-muzzolon/README.md
- projects/tp1/felipe-blanco-muzzolon/index.html
Agrego mi carpeta felipe-blanco-muzzolon, con el index.html y README, a la carpeta de tp1.
> cv-felipe-blanco-muzzolon

- projects/tp1/Violeta-Sol-Arias-Hours/index.html
- projects/tp1/Violeta-Sol-Arias-Hours/readme.md
Dejo aquí lo correspondiente al TP1, no estaba muy segura pero el commit está en Ingles y este PR en español.
> Creado el CV enn HTML y readme correspondiente al TP1

- projects/tp1/Christopher-Villalta/index.html
- projects/tp1/Christopher-Villalta/readme
> añadiendo el TP1 de Christopher Villalta

- projects/tp1/facundo-elorz/index.html
- projects/tp1/facundo-elorz/readme.md
Trabajo Práctico 1, index.html y readme.md
Facundo Elorz
> tp1-facundo-elorz

- projects/tp1/Joel-Waiman/index.html
- projects/tp1/Joel-Waiman/readme.md
> Joel waiman

- projects/tp1/Carlos-Garay/README.md
- projects/tp1/Carlos-Garay/index.html
TP pedido para el ingreso al equipo de sistema
> TP 1 hecho por Garay Carlos

- package-lock.json
- projects/tp1/Francisco-Buddemeyer/index.html
- projects/tp1/Francisco-Buddemeyer/readme.md
add index.html and readme Francisco-Buddemeyer
> Francisco-Buddemeyer

- projects/tp1/Luis-Exequiel-Schiavo/index.html
- projects/tp1/Luis-Exequiel-Schiavo/readme.md
Entrega del trabajo practico 1 Exequiel Schiavo
> TP1 Exequiel Schiavo

- projects/PN-2/readme.md
- projects/tp1/Ayrton-Nahir-Arroyo-Acevedo/index.html
- projects/tp1/Ayrton-Nahir-Arroyo-Acevedo/readme.md
> I add my name to the list
